spring.application.name=FeedbackService
spring.data.mongodb.uri=mongodb://localhost:27017/profiles
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=profiles
server.port=7020

